### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by luigitni** [RookieGameDevs/surviveler#8]
Clicking across the map may cause a division by zero.

I am unable to reproduce the issue at the moment but I got this crash twice by clicking on random map locations.

Here's the stacktrace:

```python
Traceback (most recent call last):
  File "src/client/main.py", line 131, in <module>
    bootstrap()
  File "/Volumes/LACIE_SHARE/repositories/surviveler/lib/python3.6/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Volumes/LACIE_SHARE/repositories/surviveler/lib/python3.6/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Volumes/LACIE_SHARE/repositories/surviveler/lib/python3.6/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Volumes/LACIE_SHARE/repositories/surviveler/lib/python3.6/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "src/client/main.py", line 127, in bootstrap
    main(character, config)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "src/client/main.py", line 113, in main
    client.start()
  File "/Volumes/LACIE_SHARE/repositories/surviveler/src/client/client.py", line 287, in start
    self.context.input_mgr.process_input()
  File "/Volumes/LACIE_SHARE/repositories/surviveler/src/client/core/input.py", line 49, in process_input
    state))
  File "/Volumes/LACIE_SHARE/repositories/surviveler/src/client/events.py", line 34, in send_event
    subscriber(event)
  File "/Volumes/LACIE_SHARE/repositories/surviveler/src/client/game/actions.py", line 128, in handle_mouse_click
    entity = context.pick_entity(c_pos, ray)
  File "/Volumes/LACIE_SHARE/repositories/surviveler/src/client/context.py", line 148, in pick_entity
    if intersect(pos, ray, e.bounding_box):
  File "/Volumes/LACIE_SHARE/repositories/surviveler/src/client/utils.py", line 118, in intersect
    p = intersection(pos, ray, Vec(1, 0, 0), l.x)
  File "/Volumes/LACIE_SHARE/repositories/surviveler/src/client/utils.py", line 95, in intersection
    t = -(pos.dot(norm) + d) / ray.dot(norm)
ZeroDivisionError: float division by zero
```

**Comment by duploduplo** [comment]
Bump. Any news about this problem? I'm not able to reproduce it.
